### ISSUE TITLE
GamesList render

### ISSUE THREAD

**Issue by MarsBanana** [MarsBanana/dater-test-game#18]
При первом открытии JoinScreen'a список не редерится, в console.log списки отличаются, но оба заполнены
Когда список _якобы_ пустой, ничего не рендерится, а параметр length равен 0

![изображение](https://user-images.githubusercontent.com/40831786/103237117-4b696180-4979-11eb-8ea6-52c45451f663.png)
![изображение](https://user-images.githubusercontent.com/40831786/103237171-689e3000-4979-11eb-97e3-60c4fecd96e9.png)

**Comment by olegwn** [comment]
ты пробовал играться с metadata в ответах из firebase?

https://firebase.google.com/docs/reference/unity/class/firebase/firestore/snapshot-metadata#class_firebase_1_1_firestore_1_1_snapshot_metadata

**Comment by MarsBanana** [comment]
Оба параметра из metadata всегда false
Не думаю что это как-то связано
Проблема появляется именно на этапе работы селектора, в Redux DevTools всё обновляется как нужно (с первого раза)

**Comment by olegwn** [comment]
тогда думай, решение точно есть)
